// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright (C) 2025 The ARG-V Project
/** filtered and transformed by ARG-V */

/******************************************************
 * Distributed Storage Simulator 0.1
 * by Lakshmi Ganesh, Mark Silberstein, and Yang Wang
 * see https://code.google.com/p/ds-sim/
 ******************************************************/
import org.sosy_lab.sv_benchmarks.Verifier;

public class Main {

  private double mean = Verifier.nondetDouble();
  private double stddev = Verifier.nondetDouble();
  private double startTime = Verifier.nondetDouble();
  private double minval = Verifier.nondetDouble();

  /** ARG-V: suitable */
  public double generateNextEvent(double currentTime) {
    if (currentTime < startTime) currentTime = startTime + 1;
    if (currentTime < startTime)
      throw new RuntimeException("current time is smaller than the start time");
    double nextVal = 0;
    while (nextVal < minval) {
      nextVal = (Verifier.nondetDouble() * stddev + mean);
    }
    if (nextVal < 0) nextVal = -nextVal;
    if (nextVal < 0) throw new RuntimeException("Negative value generated!");
    if (startTime + nextVal <= currentTime) {
      startTime = currentTime;
      return startTime;
    }
    return startTime + nextVal;
  }

  /** This main was generated by ARG-V */
  public static void main(String[] args) throws Exception {
    Main instance = new Main();
    instance.generateNextEvent(Verifier.nondetDouble());
  }
}
