// SPDX-FileCopyrightText: Copyright (C) 2015, Kristian Sloth Lauszus
// SPDX-License-Identifier: GPL-2.0-or-later
// SPDX-FileCopyrightText: Copyright (C) 2025 The ARG-V Project

/** filtered and transformed by ARG-V */

/*******************************************************************************
 * Copyright (C) 2015 Kristian Sloth Lauszus. All rights reserved.
 *
 * This software may be distributed and modified under the terms of the GNU
 * General Public License version 2 (GPL2) as published by the Free Software
 * Foundation and appearing in the file GPL2.TXT included in the packaging of
 * this file. Please note that GPL2 Section 2[b] requires that all works based
 * on this software must also be made publicly available under the terms of
 * the GPL2 ("Copyleft").
 *
 * Contact information
 * -------------------
 *
 * Kristian Sloth Lauszus
 * Web      :  http://www.lauszus.com
 * e-mail   :  lauszus@gmail.com
 ******************************************************************************/
import org.sosy_lab.sv_benchmarks.Verifier;

public class Main {

  private static int bufferSize = 500;
  private static double counter = bufferSize;

  private static double[][] buffer = new double[3][bufferSize + 1]; // Used to store last readings

  /** ARG-V: suitable */
  public void updateAngles(float rollValue, float pitchValue, float yawValue) {
    if (yawValue > 180) {
      yawValue -= 360;
    }
    for (int i = 0; i < 3; i++) {
      buffer[i][1] = yawValue * pitchValue * rollValue;
      System.arraycopy(buffer[i], 1, buffer[i], 0, bufferSize);
      assert buffer[i][bufferSize] == buffer[i][bufferSize - 1];
    }
    counter++;
  }

  /** This main was generated by ARG-V */
  public static void main(String[] args) throws Exception {
    Main instance = new Main();
    instance.updateAngles(Verifier.nondetFloat(), Verifier.nondetFloat(), Verifier.nondetFloat());
  }
}
