// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright (C) 2025 The ARG-V Project

/** filtered and transformed by ARG-V */

/******************************************************
 * Distributed Storage Simulator 0.1
 * by Lakshmi Ganesh, Mark Silberstein, and Yang Wang
 * see https://code.google.com/p/ds-sim/
 ******************************************************/
import org.sosy_lab.sv_benchmarks.Verifier;

public class Main {

  private double gamma = Verifier.nondetDouble();
  private double lamda = Verifier.nondetDouble();
  private double beta = Verifier.nondetDouble();
  private double startTime = Verifier.nondetDouble();
  private String name = Verifier.nondetString();

  /** ARG-V: suitable */
  public double generateNextEvent(double currentTime) {
    currentTime -= startTime;
    if (currentTime < 0) throw new RuntimeException("Negative current time!");
    double r = Verifier.nondetDouble();
    double R = Verifier.nondetDouble();
    double result = lamda * (Math.pow(-Math.log(1.0 - R), 1 / beta)) + gamma + startTime;
    if (Double.isInfinite(result) || Double.isNaN(result)) {
      System.out.println("currentTime=" + currentTime + " r=" + r + " R=" + R + " F=");
      throw new RuntimeException("generated time is Inf or NAN");
    }
    if (result < 0) throw new RuntimeException("generated time is Negative!");
    return result;
  }

  /** This main was generated by ARG-V */
  public static void main(String[] args) throws Exception {
    Main instance = new Main();
    instance.generateNextEvent(Verifier.nondetDouble());
  }
}
