// SPDX-FileCopyrightText: Copyright (C) 2009 The Android Open Source Project
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright (C) 2025 The ARG-V Project

/** filtered and transformed by ARG-V */

/*
 * Copyright (C) 2009 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;

/**
 * This class is used to listen to the accelerometer to monitor the orientation of the phone. The
 * client of this class is notified when the orientation changes between horizontal and vertical.
 */
public final class Main {
  // ------------------------------ FIELDS ------------------------------

  // Device orientation
  public static int ORIENTATION_HORIZONTAL = 2;

  public static int ORIENTATION_VERTICAL = 1;

  private static double VERTICAL_ANGLE = 50.0;

  // --------------------------- CONSTRUCTORS ---------------------------

  // -------------------------- OTHER METHODS --------------------------

  /** ARG-V: suitable */
  private void onSensorEvent(double x, double y, double z) {
    // If some values are exactly zero, then likely the sensor is not powered up yet.
    // ignore these events to avoid false horizontal positives.
    if (x == 0.0 || y == 0.0 || z == 0.0) {
      assert !(x != 0.0 && y != 0.0 && z != 0.0); // inline assert generated by ARG-V
      return;
    }

    // magnitude of the acceleration vector projected onto XY plane
    double xy = Math.sqrt(x * x + y * y);
    // compute the vertical angle
    double angle = Math.atan2(xy, z);
    // convert to degrees
    angle = angle * 180.0 / Math.PI;
    assert angle > 0.0;
    int orientation = (angle > VERTICAL_ANGLE ? ORIENTATION_VERTICAL : ORIENTATION_HORIZONTAL);
    assert orientation == 2 || orientation == 1; // inline assert generated by ARG-V
  }

  /** This main was generated by ARG-V */
  public static void main(String[] args) throws Exception {
    Main instance = new Main();
    instance.onSensorEvent(
        Verifier.nondetDouble(), Verifier.nondetDouble(), Verifier.nondetDouble());
  }

  // -------------------------- INNER CLASSES --------------------------

}
