// SPDX-FileCopyrightText: Copyright (C) 2010 Yahoo! Inc.
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright (C) 2025 The ARG-V Project

/** filtered and transformed by ARG-V */

/**
 * Copyright (c) 2010 Yahoo! Inc. All rights reserved.
 *
 * <p>Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
 * except in compliance with the License. You may obtain a copy of the License at
 *
 * <p>http://www.apache.org/licenses/LICENSE-2.0
 *
 * <p>Unless required by applicable law or agreed to in writing, software distributed under the
 * License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing permissions and
 * limitations under the License. See accompanying LICENSE file.
 */
import org.sosy_lab.sv_benchmarks.Verifier;

/**
 * Generate integers resembling a hotspot distribution where x% of operations access y% of data
 * items. The parameters specify the bounds for the numbers, the percentage of the of the interval
 * which comprises the hot set and the percentage of operations that access the hot set. Numbers of
 * the hot set are always smaller than any number in the cold set. Elements from the hot set and the
 * cold set are chose using a uniform distribution.
 *
 * @author sudipto
 */
public class Main {

  public int lowerBound = Verifier.nondetInt();
  public int upperBound = Verifier.nondetInt();
  public int hotInterval = Verifier.nondetInt();
  public int coldInterval = Verifier.nondetInt();
  public double hotsetFraction = Verifier.nondetDouble();
  public double hotOpnFraction = Verifier.nondetDouble();

  /**
   * Create a generator for Hotspot distributions.
   *
   * @param lowerBound lower bound of the distribution.
   * @param upperBound upper bound of the distribution.
   * @param hotsetFraction percentage of data item
   * @param hotOpnFraction percentage of operations accessing the hot set.
   */
  /** ARG-V: suitable */
  public Main(int lowerBound, int upperBound, double hotsetFraction, double hotOpnFraction) {
    if (hotsetFraction < 0.0 || hotsetFraction > 1.0) {
      System.err.println("Hotset fraction out of range. Setting to 0.0");
      hotsetFraction = 0.0;
    }
    if (hotOpnFraction < 0.0 || hotOpnFraction > 1.0) {
      System.err.println("Hot operation fraction out of range. Setting to 0.0");
      hotOpnFraction = 0.0;
    }
    if (lowerBound > upperBound) {
      System.err.println(
          "Upper bound of Hotspot generator smaller than the lower bound. "
              + "Swapping the values.");
      int temp = lowerBound;
      lowerBound = upperBound;
      upperBound = temp;
    }
    this.lowerBound = lowerBound;
    this.upperBound = upperBound;
    this.hotsetFraction = hotsetFraction;
    int interval = upperBound - lowerBound + 1;
    this.hotInterval = (int) (interval * hotsetFraction);
    this.coldInterval = interval - hotInterval;
    this.hotOpnFraction = hotOpnFraction;
  }

  /** This main was generated by ARG-V */
  public static void main(String[] args) throws Exception {
    double _hotsetFraction = Verifier.nondetDouble();
    Verifier.assume(_hotsetFraction > 0.0);
    double _hotOpnFraction = Verifier.nondetDouble();
    Verifier.assume(_hotOpnFraction > 0.0);
    Main instance =
        new Main(Verifier.nondetInt(), Verifier.nondetInt(), _hotsetFraction, _hotOpnFraction);
    assert instance.hotOpnFraction >= 0.0 && instance.hotOpnFraction <= 1.0;
    assert instance.upperBound >= instance.lowerBound;
    assert instance.hotsetFraction >= 0.0 && instance.hotsetFraction <= 1.0;
  }
}
