// SPDX-FileCopyrightText: Copyright (C) 2001 Kevin Boone/Web-Tomorrow
// SPDX-License-Identifier: GPL-3.0-or-later
// SPDX-FileCopyrightText: Copyright (C) 2025 The ARG-V Project

/** filtered and transformed by ARG-V */
import org.sosy_lab.sv_benchmarks.Verifier;

/**
 * %%Ignore-License Java class for calculating sunset and sunrise times.
 *
 * <p>This class exposes two methods only: getSunsetTimeUTC and getSunriseTimeUTC. Both take all the
 * parameters necessary to make the calculation; that is, nothing is assumed, and no system
 * information is used. If the caller wants to make, for example, the current year or geographical
 * location the default, then it has to do that itself. The caller also needs to supply the Sun's
 * zenith, which is subject to some interpretation. For most purposes, the constant ZENITH defined
 * in this class will do the trick for true sunrise and sunset. There are other zenith constants for
 * various types of twilight.
 *
 * <p>The methods in this class return a UTC time, not a local time. This allows its operation to be
 * independent of the system. If the caller requires a local time, which is likely, it needs to
 * convert it. Methods are provided in the Java <code>TimeZone</code> class to do this, but they
 * rely on the system time zone and clock to be correct.
 *
 * <p>See the overview for details of how to use this class<br>
 * PS: for testing purposes, London UK is latitude 51, longitude 0
 *
 * <p>(c)2001 Kevin Boone/Web-Tomorrow, all rights reserved
 */
public class Main {

  /**
   * Calculates the Sun's true longitude in degrees. The result is an angle gte 0 and lt 360.
   * Requires the Sun's mean anomaly, also in degrees
   *
   * @param sunMeanAnomaly
   * @return
   */
  /** ARG-V: suitable */
  private static double getSunTrueLongitude(double sunMeanAnomaly) {
    double l = Verifier.nondetDouble();
    Verifier.assume(l == l); // ensures that l is not NaN
    // get longitude into 0-360 degree range
    if (l >= 360.0) {
      l = 360.0;
    }
    if (l < 0) {
      l = 360.0;
    }
    assert l <= 360.0 && l >= 0.0; // inline assert generated by ARG-V
    return l + sunMeanAnomaly;
  }

  /** This main was generated by ARG-V */
  public static void main(String[] args) throws Exception {
    getSunTrueLongitude(Verifier.nondetDouble() * Verifier.nondetInt());
  }
}
