// SPDX-FileCopyrightText: Copyright (C) 2006, Jerry Huxtable
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright (C) 2025 The ARG-V Project
/** filtered and transformed by ARG-V */
import org.sosy_lab.sv_benchmarks.Verifier;

public class Main {
  private int gridSize = 4;
  // Index OOB Exception: Array Size too small
  private double[] gridExtent = new double[] {Verifier.nondetDouble()};

  /** ARG-V: suitable */
  public boolean runGrid(double tolerance) {

    double minx = gridExtent[0];
    double miny = gridExtent[1];
    double maxx = gridExtent[2];
    double maxy = gridExtent[3];

    double dx = (maxx - minx) / gridSize;
    double dy = (maxy - miny) / gridSize;
    for (int ix = 0; ix <= gridSize; ix++) {
      for (int iy = 0; iy <= gridSize; iy++) {
        boolean isWithinTol = Verifier.nondetBoolean();
        if (!isWithinTol) return false;
      }
    }
    return true;
  }

  private static void updateLat(double lat, double[] latExtent) {
    // 0.0 indicates not set (for most projections?)
    if (lat == 0.0) return;
    if (lat < latExtent[0]) {
      latExtent[0] = lat;
    }
    if (lat > latExtent[1]) {
      latExtent[1] = lat;
    }
  }

  /** This main was generated by ARG-V */
  public static void main(String[] args) throws Exception {
    Main instance = new Main();
    instance.runGrid(Verifier.nondetDouble());
    updateLat(
        Verifier.nondetDouble(), new double[] {Verifier.nondetDouble(), Verifier.nondetDouble()});
  }
}
