// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright (C) 2025 The ARG-V Project

/** filtered and transformed by ARG-V */
import org.sosy_lab.sv_benchmarks.Verifier;

/**
 * Helper class that provide static methods for calculating correlation value between two objects.
 */
/** filtered by ARG-V */
public class Main {

  /**
   * Calculate the pearson correlation coefficient betwen two items using the given values. The
   * correlation is calculated according to the formula stated in {@link
   * http://www.grouplens.org/papers/pdf/www10_sarwar.pdf} (section 3.1.2).
   *
   * @param xPowSum sum of the first item ratings when every rating value is power by 2. the value
   *     is used for the counter calculation as appear in the formula.
   * @param yPowSum sum of the second item ratings when every rating value is power by 2. the value
   *     is used for the counter calculation as appear in the formula.
   * @param xySum the value of the counter in the correlation formula.
   * @return the correlation value between two items.
   */
  /** ARG-V: suitable */
  public static double getPearsonCorrelationCoefficient(
      double xySum, double xPowSum, double yPowSum) {
    int denominator = (int) (Math.sqrt(xPowSum) * Math.sqrt(yPowSum));

    double retVal = Verifier.nondetDouble();

    if (denominator == 0) {
      retVal = 0;
    } else {
      retVal = ((int) xySum / denominator);
    }

    return retVal;
  }

  /** This main was generated by ARG-V */
  public static void main(String[] args) throws Exception {
    getPearsonCorrelationCoefficient(
        Verifier.nondetDouble(), Verifier.nondetDouble(), Verifier.nondetDouble());
  }
}
