// SPDX-FileCopyrightText: Copyright (c) 2014-2015 The Board of Trustees of Leland Stanford Junior
// University
// SPDX-FileCopyrightText: Copyright (c) 2014-2015, Marcus R. Breese
// SPDX-License-Identifier: BSD-3-Clause
// SPDX-FileCopyrightText: Copyright (C) 2025 The ARG-V Project

/** filtered and transformed by ARG-V */
import org.sosy_lab.sv_benchmarks.Verifier;

public class Main {

  private int min = -1;
  private int max = Verifier.nondetInt();

  private long totalCount = 0;
  private long missing = 0;

  private long acc = 0;

  //    private boolean inclusive = false;

  /**
   * @param pct 0..1
   * @return
   */
  /** ARG-V: suitable */
  public int getQuantile(double pct) {
    double thres = pct * totalCount;
    long count = -1;

    for (int i = min; i <= max && count < thres; i++) {
      count += Verifier.nondetLong();
      if (count > thres) {
        assert thres == 0; // inline assert generated by ARG-V
        return i;
      }
    }

    assert count > -1; // inline assert generated by ARG-V
    return (int) count;
  }

  /** This main was generated by ARG-V */
  public static void main(String[] args) throws Exception {
    Main instance = new Main();
    instance.getQuantile(Verifier.nondetDouble());
  }
}
