// SPDX-FileCopyrightText: Copyright (C) 2006, Jerry Huxtable
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright (C) 2025 The ARG-V Project
/** filtered and transformed by ARG-V */

/*
Copyright 2006 Jerry Huxtable

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import org.sosy_lab.sv_benchmarks.Verifier;

/** filtered by ARG-V */
public class Main {

  /** ARG-V: suitable */
  public static double asin(double v) {
    if (Math.abs(v) > 1.) return v < 0.0 ? -Math.PI / 2 : Math.PI / 2;
    return Math.asin(v);
  }

  public static double acos(double v) {
    if (Math.abs(v) > 1.) return v < 0.0 ? Math.PI : 0.0;
    return Math.acos(v);
  }

  /** ARG-V: suitable */
  public static double hypot(int x, int y) {
    // Removed safety checks and used ints; could throw ArithmeticException
    if (x < y) {
      x /= y;
      return y * Math.sqrt(1.0 + x * x);
    } else {
      y /= x;
      return x * Math.sqrt(1.0 + y * y);
    }
  }

  // For negative angles, d should be negative, m & s positive.
  /** ARG-V: suitable */
  public static double dmsToRad(double d, double m, double s) {
    if (d >= 0) return (d + m / 60 + s / 3600) * Math.PI / 180.0;
    return (d - m / 60 - s / 3600) * Math.PI / 180.0;
  }

  // For negative angles, d should be negative, m & s positive.
  /** ARG-V: suitable */
  public static double dmsToDeg(double d, double m, double s) {
    if (d >= 0) return (d + m / 60 + s / 3600);
    return (d - m / 60 - s / 3600);
  }

  /** ARG-V: suitable */
  public static double takeSign(double a, double b) {
    a = Math.abs(a);
    if (b < 0) return -a;
    return a;
  }

  /** ARG-V: suitable */
  public static double qsfn(double sinphi, double e, double one_es) {
    double con = Verifier.nondetDouble();

    if (e >= 1.0e-7) {
      con = e * sinphi;
      return (one_es * (sinphi / (1. - con * con) - (.5 / e) * Math.log((1. - con) / (1. + con))));
    } else return (sinphi + sinphi);
  }

  /*
   * Java translation of "Nice Numbers for Graph Labels"
   * by Paul Heckbert
   * from "Graphics Gems", Academic Press, 1990
   */
  /** ARG-V: suitable */
  public static double niceNumber(double x, boolean round) {
    int expv = Verifier.nondetInt(); /* exponent of x */
    double f = Verifier.nondetDouble(); /* fractional part of x */
    double nf = Verifier.nondetDouble(); /* nice, rounded fraction */

    expv = (int) Math.floor(Math.log(x) / Math.log(10));
    f = x / Math.pow(10., expv); /* between 1 and 10 */
    if (round) {
      if (f < 1.5) {
        nf = 1.;
      } else if (f < 3.) {
        nf = 2.;
      } else if (f < 7.) {
        nf = 5.;
      } else nf = 10.;
    } else if (f <= 1.) {
      nf = 1.;
    } else if (f <= 2.) {
      nf = 2.;
    } else if (f <= 5.) {
      nf = 5.;
    } else nf = 10.;
    return nf * Math.pow(10., expv);
  }

  /** This main was generated by ARG-V */
  public static void main(String[] args) throws Exception {
    asin(Verifier.nondetDouble());
    acos(Verifier.nondetDouble());
    hypot(Verifier.nondetInt(), Verifier.nondetInt());
    dmsToRad(Verifier.nondetDouble(), Verifier.nondetDouble(), Verifier.nondetDouble());
    dmsToDeg(Verifier.nondetDouble(), Verifier.nondetDouble(), Verifier.nondetDouble());
    takeSign(Verifier.nondetDouble(), Verifier.nondetDouble());
    qsfn(Verifier.nondetDouble(), Verifier.nondetDouble(), Verifier.nondetDouble());
    niceNumber(Verifier.nondetDouble(), Verifier.nondetBoolean());
  }
}
