// SPDX-FileCopyrightText: Copyright (C) 2014-2015 Sky Welch
// SPDX-License-Identifier: GPL-3.0-or-later
// SPDX-FileCopyrightText: Copyright (C) 2025 The ARG-V Project

/** filtered and transformed by ARG-V */
import org.sosy_lab.sv_benchmarks.Verifier;

public class Main {
  // Dragging/scaling control variables
  private float dragLastX = 0;
  private float dragLastY = 0;

  public float totalDragX = 0;
  public float totalDragY = 0;

  /** ARG-V: suitable */
  public void dragFractal(float x, float y) {
    float dragDiffPixelsX = Verifier.nondetFloat();
    float dragDiffPixelsY = Verifier.nondetFloat();

    try {
      dragDiffPixelsX = x - dragLastX;
      dragDiffPixelsY = y - dragLastY;
    } catch (Exception e) {
      return;
    }

    // Move the canvas
    if (dragDiffPixelsX != 0.0f && dragDiffPixelsY != 0.0f) {
      this.totalDragX += dragDiffPixelsX;
      this.totalDragY += dragDiffPixelsY;
    }

    // Update last mouse position
    this.dragLastX = x;
    this.dragLastY = y;
  }

  /** This main was generated by ARG-V */
  public static void main(String[] args) throws Exception {
    float x = Verifier.nondetFloat();
    float y = Verifier.nondetFloat();
    Main instance = new Main();
    instance.dragFractal(x, y);
    instance.dragFractal(x + 0.1f, y + 0.1f);
    if (!Double.isNaN(x) && !Double.isNaN(y)) {
      assert instance.totalDragX == x;
      assert instance.totalDragY == y;
    }
  }
}
