// SPDX-FileCopyrightText: Copyright (C) 2006, Jerry Huxtable
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright (C) 2025 The ARG-V Project
/** filtered and transformed by ARG-V */

/*
Copyright 2006 Jerry Huxtable

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
/*
 * This file was semi-automatically converted from the public-domain USGS PROJ source.
 */
import org.sosy_lab.sv_benchmarks.Verifier;

public class Main {

  private static int N_ITER = 15;
  private static double EPSILON = 1.0e-7;
  private static double TOL = 1.0e-10;

  // protected double projectionLatitude1 = MapMath.degToRad(45.5);
  // protected double projectionLatitude2 = MapMath.degToRad(29.5);

  /** ARG-V: suitable */
  private static double phi1_(double qs, double Te, double Tone_es) {
    double sinpi = Verifier.nondetDouble();
    double cospi = Verifier.nondetDouble();
    double con = Verifier.nondetDouble();
    double com = Verifier.nondetDouble();
    double dphi = Verifier.nondetDouble();

    double Phi = Math.asin(.5 * qs);
    if (Te < EPSILON) return Phi;
    int i = N_ITER;
    do {
      sinpi = Math.sin(Phi);
      cospi = Math.cos(Phi);
      con = Te * sinpi;
      com = 1. - con * con;
      dphi =
          .5
              * com
              * com
              / cospi
              * (qs / Tone_es - sinpi / com + .5 / Te * Math.log((1. - con) / (1. + con)));
      Phi += dphi;
    } while (Math.abs(dphi) > TOL && --i != 0);
    return (i != 0 ? Phi : Double.MAX_VALUE);
  }

  /** This main was generated by ARG-V */
  public static void main(String[] args) throws Exception {
    double result =
        phi1_(Verifier.nondetDouble(), Verifier.nondetDouble(), Verifier.nondetDouble());
    assert result <= 0;
  }
}
