// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright (C) 2025 The ARG-V Project

/** filtered and transformed by ARG-V */

/******************************************************
 * Distributed Storage Simulator 0.1
 * by Lakshmi Ganesh, Mark Silberstein, and Yang Wang
 * see https://code.google.com/p/ds-sim/
 ******************************************************/
import org.sosy_lab.sv_benchmarks.Verifier;

public class Main {

  private double gamma = Verifier.nondetDouble();
  private double lamda = Verifier.nondetDouble();
  private double beta = Verifier.nondetDouble() * 5;
  private double startTime = Verifier.nondetDouble();
  private String name = Verifier.nondetString();

  /** ARG-V: suitable */
  public double generateNextEvent(double currentTime) {
    currentTime -= startTime;
    if (currentTime < 0) currentTime = -currentTime;
    if (currentTime < 0) throw new RuntimeException("Negative current time!");
    double r = Verifier.nondetDouble();
    double R = 0.5;
    if (Double.isNaN(lamda) || Double.isInfinite(lamda)) {
      lamda = 0.0;
    }
    if (Double.isNaN(beta) || Double.isInfinite(beta) || beta == 0.0) {
      beta = 1.0;
    }
    if (Double.isNaN(gamma) || Double.isInfinite(gamma)) {
      gamma = 0.0;
    }
    if (Double.isNaN(startTime) || Double.isInfinite(startTime)) {
      startTime = 0.0;
    }
    double result = lamda * (Math.pow(-Math.log(1.0 - R), (int) (1 / beta))) + gamma + startTime;
    if (Double.isNaN(result)) {
      System.out.println("currentTime=" + currentTime + " r=" + r + " R=" + R + " F=");
      throw new RuntimeException("generated time is or NAN");
    }
    return result;
  }

  /** This main was generated by ARG-V */
  public static void main(String[] args) throws Exception {
    Main instance = new Main();
    instance.generateNextEvent(Verifier.nondetDouble());
  }
}
