// SPDX-License-Identifier: GPL-3.0-or-later
// SPDX-FileCopyrightText: Copyright (C) 2025 The ARG-V Project

/** filtered and transformed by ARG-V */
import org.sosy_lab.sv_benchmarks.Verifier;

public class Main {

  /** ARG-V: suitable */
  public float getInterpolation(float t) {
    float x = t * 2.0f;
    if (t < 0.5f) return 0.5f * x * x * x * x * x;
    return 0.5f * x * x * x * x * x + 1;
  }

  /** This main was generated by ARG-V */
  public static void main(String[] args) throws Exception {
    Main instance = new Main();
    float input = Verifier.nondetFloat();
    if (Math.abs(input) <= 100.0f) {
      float result = instance.getInterpolation(input);
      assert Math.abs(input * input * input * input * input * 16.0f - result) < 1.1f;
    }
  }
}
