// SPDX-FileCopyrightText: Copyright (C) 2006, Jerry Huxtable
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright (C) 2025 The ARG-V Project
/** filtered and transformed by ARG-V */

/*
Copyright 2006 Jerry Huxtable

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
/*
 * This file was semi-automatically converted from the public-domain USGS PROJ source.
 */
import org.sosy_lab.sv_benchmarks.Verifier;

/** The Equidistant Conic projection. */
public class Main {

  private double standardLatitude1 = Verifier.nondetDouble();
  private double standardLatitude2 = Verifier.nondetDouble();

  private double eccentricity = 0.822719;
  private double eccentricity2 = eccentricity * eccentricity;
  private double radius = 1;

  private boolean northPole = Verifier.nondetBoolean();
  private double f = Verifier.nondetDouble(),
      n = Verifier.nondetDouble(),
      rho0 = Verifier.nondetDouble();

  /** ARG-V: suitable */
  private void initialize(
      double rlong0, double rlat0, double standardLatitude1, double standardLatitude2) {
    double rho0 = Verifier.nondetDouble();
    double n = Verifier.nondetDouble();
    double t_rlat0 = Verifier.nondetDouble();

    northPole = rlat0 > 0.0;
    double t_standardLatitude1 = Verifier.nondetDouble();
    double m_standardLatitude1 =
        Math.cos(standardLatitude1)
            / Math.sqrt(1.0 - eccentricity2 * Math.pow(Math.sin(standardLatitude1), 2.0));
    double t_standardLatitude2 = Verifier.nondetDouble();
    double m_standardLatitude2 =
        Math.cos(standardLatitude2)
            / Math.sqrt(1.0 - eccentricity2 * Math.pow(Math.sin(standardLatitude2), 2.0));
    t_rlat0 = Verifier.nondetDouble();

    if (standardLatitude1 != standardLatitude2) {
      n =
          (Math.log(m_standardLatitude1) - Math.log(m_standardLatitude2))
              / (Math.log(t_standardLatitude1) - Math.log(t_standardLatitude2));
      assert Math.sin(standardLatitude1) != Math.sin(standardLatitude2);
    } else {
      n = Math.sin(standardLatitude1);
    }

    f = m_standardLatitude1 / (n * Math.pow(t_standardLatitude1, n));
    rho0 = radius * f * Math.pow(t_rlat0, n);
  }

  /** This main was generated by ARG-V */
  public static void main(String[] args) throws Exception {
    Main instance = new Main();
    instance.initialize(
        Verifier.nondetDouble(),
        Verifier.nondetDouble(),
        Verifier.nondetDouble() * Verifier.nondetInt(),
        Verifier.nondetDouble() * Verifier.nondetInt());
  }
}
