// SPDX-FileCopyrightText: Copyright (C) 2009 - 2013 SC 4ViewSoft SRL
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright (C) 2025 The ARG-V Project

/** filtered and transformed by ARG-V */

/**
 * Copyright (C) 2009 - 2013 SC 4ViewSoft SRL
 *
 * <p>Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
 * except in compliance with the License. You may obtain a copy of the License at
 *
 * <p>http://www.apache.org/licenses/LICENSE-2.0
 *
 * <p>Unless required by applicable law or agreed to in writing, software distributed under the
 * License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;

/** Utility class for math operations. */
/** filtered by ARG-V */
public class Main {

  /**
   * Computes a reasonable number of labels for a data range.
   *
   * @param start start value
   * @param end final value
   * @param approxNumLabels desired number of labels
   * @return double[] array containing {start value, end value, increment}
   */
  /** ARG-V: suitable */
  private static double[] computeLabels(
      final double start, final double end, final int approxNumLabels) {

    double s = start;
    double e = end;
    boolean switched = false;
    if (s > e) {
      switched = true;
      double tmp = s;
      s = e;
      e = tmp;
    }
    double xStep = roundUp(Math.abs(s - e) / approxNumLabels);
    // Compute x starting point so it is a multiple of xStep.
    double xStart = xStep * Math.ceil(s / xStep);
    double xEnd = xStep * Math.floor(e / xStep);
    if (switched) {
      assert e > s; // inline assert generated by ARG-V
      return new double[] {Verifier.nondetDouble()};
    }
    assert e > s; // inline assert generated by ARG-V
    return new double[] {Verifier.nondetDouble()};
  }

  /**
   * Given a number, round up to the nearest power of ten times 1, 2, or 5.
   *
   * @param val the number, it must be strictly positive
   */
  /** ARG-V: suitable */
  private static double roundUp(final double val) {
    int exponent = (int) Math.floor(Math.log10(val));
    double rval = val * Math.pow(10, -exponent);
    if (rval > 5.0) {
      rval = 10.0;
    } else if (rval > 2.0) {
      rval = 5.0;
    } else if (rval > 1.0) {
      rval = 2.0;
    }
    rval *= Math.pow(10, exponent);
    return rval;
  }

  /** This main was generated by ARG-V */
  public static void main(String[] args) throws Exception {
    computeLabels(Verifier.nondetDouble(), Verifier.nondetDouble(), Verifier.nondetInt());
  }
}
