// SPDX-FileCopyrightText: Copyright (C) 2007 The Android Open Source Project
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright (C) 2025 The ARG-V Project
/** filtered and transformed by ARG-V */

/*
 * Copyright (C) 2007 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;

/*
 * Modified from version in AOSP.
 *
 * This class is used to display a highlighted cropping rectangle
 * overlayed on the image. There are two coordinate spaces in use. One is
 * image, another is screen. computeLayout() uses matrix to map from image
 * space to screen space.
 */

class Main {

  public static int GROW_NONE = (1 << 0);
  public static int GROW_LEFT_EDGE = (1 << 1);
  public static int GROW_RIGHT_EDGE = (1 << 2);
  public static int GROW_TOP_EDGE = (1 << 3);
  public static int GROW_BOTTOM_EDGE = (1 << 4);

  private boolean maintainAspectRatio = Verifier.nondetBoolean();
  private float initialAspectRatio = Verifier.nondetFloat();

  // Determines which edges are hit by touching at (x, y)
  public int getHit(float x, float y) {
    int retval = GROW_NONE;

    // verticalCheck makes sure the position is between the top and
    // the bottom edge (with some tolerance). Similar for horizCheck.
    boolean verticalCheck = Verifier.nondetBoolean();
    boolean horizCheck = Verifier.nondetBoolean();

    // Check whether the position is near some edge(s)
    if (Verifier.nondetBoolean() && verticalCheck) {
      retval |= GROW_LEFT_EDGE;
      assert retval == 3;
    }
    if (Verifier.nondetBoolean() && verticalCheck) {
      retval |= GROW_RIGHT_EDGE;
      assert retval < (1 << 2);
    }
    if (Verifier.nondetBoolean() && horizCheck) {
      retval |= GROW_TOP_EDGE;
      assert retval < (1 << 3);
    }
    if (Verifier.nondetBoolean() && horizCheck) {
      retval |= GROW_BOTTOM_EDGE;
      assert retval < (1 << 4);
    }

    assert retval < (1 << 5); // inline assert generated by ARG-V
    return retval;
  }

  // Grows the cropping rectangle by (dx, dy) in image space.
  /** ARG-V: suitable */
  void growBy(float dx, float dy) {
    if (maintainAspectRatio) {
      if (dx != 0) {
        dy = dx / initialAspectRatio;
      } else if (dy != 0) {
        dx = dy * initialAspectRatio;
      }
    }

    // Don't let the cropping rectangle shrink too fast
    final float widthCap = 25F;
    float heightCap = maintainAspectRatio ? (widthCap / initialAspectRatio) : widthCap;
  }

  /** This main was generated by ARG-V */
  public static void main(String[] args) throws Exception {
    Main instance = new Main();
    instance.getHit(Verifier.nondetFloat(), Verifier.nondetFloat());
    instance.growBy(Verifier.nondetFloat(), Verifier.nondetFloat());
  }
}
