// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright (C) 2025 The ARG-V Project
/** filtered and transformed by ARG-V */

/******************************************************
 * Distributed Storage Simulator 0.1
 * by Lakshmi Ganesh, Mark Silberstein, and Yang Wang
 * see https://code.google.com/p/ds-sim/
 ******************************************************/
import org.sosy_lab.sv_benchmarks.Verifier;

public class Main {

  double frequency = Verifier.nondetDouble();
  double previousEvent = 0;
  /** ARG-V: suitable */
  public double generateNextEvent(double currentTime) {
    if (previousEvent + frequency <= currentTime) {
      previousEvent = currentTime;
      assert previousEvent + frequency > currentTime; // inline assert generated by ARG-V
      return previousEvent;
    }
    assert previousEvent + frequency > currentTime; // inline assert generated by ARG-V
    return previousEvent + frequency;
  }
  /** This main was generated by ARG-V */
  public static void main(String[] args) throws Exception {
    Main instance = new Main();
    instance.generateNextEvent(Verifier.nondetDouble());
    instance.generateNextEvent(Verifier.nondetDouble()); // testing tracking of mutability
  }
}
