// SPDX-FileCopyrightText: Copyright (C) 2009 - 2013 SC 4ViewSoft SRL
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright (C) 2025 The ARG-V Project

/** filtered and transformed by ARG-V */

/**
 * Copyright (C) 2009 - 2013 SC 4ViewSoft SRL
 *
 * <p>Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
 * except in compliance with the License. You may obtain a copy of the License at
 *
 * <p>http://www.apache.org/licenses/LICENSE-2.0
 *
 * <p>Unless required by applicable law or agreed to in writing, software distributed under the
 * License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;

/** Holds An PieChart Segment */
/** filtered by ARG-V */
public class Main {
  private float mStartAngle = Verifier.nondetFloat();

  private float mEndAngle = Verifier.nondetFloat();

  /**
   * Checks if angle falls in segment.
   *
   * @param angle
   * @return true if in segment, false otherwise.
   */
  /** ARG-V: suitable */
  public boolean isInSegment(double angle) {
    if (angle >= mStartAngle && angle <= mEndAngle) {
      return true;
    }
    double cAngle = angle % 360;
    double startAngle = mStartAngle;
    double stopAngle = mEndAngle;
    while (stopAngle > 360) {
      startAngle -= 360;
      stopAngle -= 360;
    }
    assert cAngle >= -180.0 && cAngle <= 180.0; // inline assert generated by ARG-V
    return cAngle >= startAngle && cAngle <= stopAngle;
  }

  /** This main was generated by ARG-V */
  public static void main(String[] args) throws Exception {
    Main instance = new Main();
    instance.isInSegment(Verifier.nondetDouble() * Verifier.nondetInt());
  }
}
