// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright (C) 2025 The ARG-V Project
/** filtered and transformed by ARG-V */

/******************************************************
 * Distributed Storage Simulator 0.1
 * by Lakshmi Ganesh, Mark Silberstein, and Yang Wang
 * see https://code.google.com/p/ds-sim/
 ******************************************************/
import org.sosy_lab.sv_benchmarks.Verifier;

public class Main {

  double previousEvent = 0;

  double values[] = new double[] {Verifier.nondetDouble()};
  double intervals[] = new double[] {Verifier.nondetDouble(), Verifier.nondetDouble()};

  /** ARG-V: suitable */
  public double generateNextEvent(double currentTime) {
    float index = Verifier.nondetFloat();
    Verifier.assume(0.0f <= index && index < Float.POSITIVE_INFINITY);
    float range = Verifier.nondetFloat();
    Verifier.assume(0.0f <= range && range < Float.POSITIVE_INFINITY);

    int i = 0;
    for (i = 0; i < values.length; i++) {
      if (index >= intervals[i] && index < intervals[i + 1]) break;
    }
    assert i <= values.length;
    if (i == 0) i++;
    double nextEvent = values[i - 1] + range * (values[i - 1] - values[0]);

    if (previousEvent + nextEvent <= currentTime) {
      previousEvent = currentTime;
      return previousEvent;
    }
    assert previousEvent + nextEvent > currentTime; // inline assert generated by ARG-V
    return previousEvent + nextEvent;
  }

  /** This main was generated by ARG-V */
  public static void main(String[] args) throws Exception {
    Main instance = new Main();
    Verifier.assume(
        0.0 <= instance.intervals[0] && instance.intervals[0] < Double.POSITIVE_INFINITY);
    Verifier.assume(
        0.0 <= instance.intervals[1] && instance.intervals[1] < Double.POSITIVE_INFINITY);
    Verifier.assume(0.0 <= instance.values[0] && instance.values[0] < Double.POSITIVE_INFINITY);
    double currentTime = Verifier.nondetDouble();
    Verifier.assume(0.0 <= currentTime && currentTime < Double.POSITIVE_INFINITY);
    instance.generateNextEvent(currentTime);
  }
}
