// SPDX-FileCopyrightText: Copyright (C) 2009 - 2013 SC 4ViewSoft SRL
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright (C) 2025 The ARG-V Project

/** filtered and transformed by ARG-V */

/**
 * Copyright (C) 2009 - 2013 SC 4ViewSoft SRL
 *
 * <p>Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
 * except in compliance with the License. You may obtain a copy of the License at
 *
 * <p>http://www.apache.org/licenses/LICENSE-2.0
 *
 * <p>Unless required by applicable law or agreed to in writing, software distributed under the
 * License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;

/** The pan tool. */
public class Main {
  /** Pan limits reached on the X axis. */
  private boolean limitsReachedX = false;
  /** Pan limits reached on the X axis. */
  private boolean limitsReachedY = false;

  /**
   * Apply the tool.
   *
   * @param oldX the previous location on X axis
   * @param oldY the previous location on Y axis
   * @param newX the current location on X axis
   * @param newY the current location on the Y axis
   */
  /** ARG-V: suitable */
  public void apply(float oldX, float oldY, float newX, float newY) {
    boolean notLimitedUp = true;
    boolean notLimitedBottom = true;
    boolean notLimitedLeft = true;
    boolean notLimitedRight = true;
    if (Verifier.nondetBoolean()) {
      int scales = Verifier.nondetInt();
      double[] limits = new double[] {Verifier.nondetDouble()};
      boolean limited = limits != null && limits.length == 4;
      for (int i = 0; i < scales; i++) {
        double[] range = new double[] {Verifier.nondetDouble()};
        double[] calcRange = new double[] {Verifier.nondetDouble()};
        if (limitsReachedX
            && limitsReachedY
            && (range[0] == range[1] && calcRange[0] == calcRange[1]
                || range[2] == range[3] && calcRange[2] == calcRange[3])) {
          return;
        }
        double[] realPoint = new double[] {Verifier.nondetDouble()};
        double[] realPoint2 = new double[] {Verifier.nondetDouble()};
        double deltaX = realPoint[0] - realPoint2[0];
        double deltaY = realPoint[1] - realPoint2[1];
        double ratio = Verifier.nondetDouble();
        if (Verifier.nondetBoolean()) {
          double newDeltaX = -deltaY * ratio;
          double newDeltaY = deltaX / ratio;
          deltaX = newDeltaX;
          deltaY = newDeltaY;
        }
        if (Verifier.nondetBoolean()) {
          if (limits != null) {
            if (notLimitedLeft) {
              notLimitedLeft = limits[0] <= range[0] + deltaX;
            }
            if (notLimitedRight) {
              notLimitedRight = limits[1] >= range[1] + deltaX;
            }
          }
          if (!limited || (notLimitedLeft && notLimitedRight)) {
            limitsReachedX = false;
          } else {
            limitsReachedX = true;
          }
        }
        if (Verifier.nondetBoolean()) {
          if (limits != null) {
            if (notLimitedBottom) {
              notLimitedBottom = limits[2] <= range[2] + deltaY;
            }
            if (notLimitedUp) {
              notLimitedUp = limits[3] >= range[3] + deltaY;
            }
          }
          if (!limited || (notLimitedBottom && notLimitedUp)) {
            limitsReachedY = false;
          } else {
            limitsReachedY = true;
          }
        }
      }
    }
  }

  /** This main was generated by ARG-V */
  public static void main(String[] args) throws Exception {
    Main instance = new Main();
    instance.apply(
        Verifier.nondetFloat(),
        Verifier.nondetFloat(),
        Verifier.nondetFloat(),
        Verifier.nondetFloat());
  }
}
