// SPDX-License-Identifier: GPL-3.0-or-later
// SPDX-FileCopyrightText: Copyright (C) 2025 The ARG-V Project
/** filtered and transformed by ARG-V */

/*************************************************************************
 *  Compilation:  javac StdAudio.java
 *  Execution:    java StdAudio
 *
 *  Simple library for reading, writing, and manipulating .wav files.
 *
 *
 *  Limitations
 *  -----------
 *    - Does not seem to work properly when reading .wav files from a .jar file.
 *    - Assumes the audio is monaural, with sampling rate of 44,100.
 *
 *************************************************************************/
import java.applet.*;
import java.io.*;
import java.net.*;
import javax.sound.sampled.*;
import org.sosy_lab.sv_benchmarks.Verifier;

/**
 * <i>Standard audio</i>. This class provides a basic capability for creating, reading, and saving
 * audio.
 *
 * <p>The audio format uses a sampling rate of 44,100 (CD quality audio), 16-bit, monaural.
 *
 * <p>For additional documentation, see <a href="http://introcs.cs.princeton.edu/15inout">Section
 * 1.5</a> of <i>Introduction to Programming in Java: An Interdisciplinary Approach</i> by Robert
 * Sedgewick and Kevin Wayne.
 *
 * @author Robert Sedgewick
 * @author Kevin Wayne
 */
public final class Main {

  private static double MAX_16_BIT = Short.MAX_VALUE; // 32,767

  private static SourceDataLine line = null; // to play the sound
  private static byte[] buffer =
      new byte[] {Verifier.nondetByte(), Verifier.nondetByte()}; // our internal buffer
  private static int bufferSize = 0; // number of samples currently in internal buffer

  /**
   * Write one sample (between -1.0 and +1.0) to standard audio. If the sample is outside the range,
   * it will be clipped.
   */
  /** ARG-V: suitable */
  public static void play(double in) {

    // clip if outside [-1, +1]
    if (in < -1.0) {
      in = -1.0;
    }
    if (in > +1.0) {
      in = +1.0;
    }

    // convert to bytes
    short s = (short) (MAX_16_BIT * in);
    buffer[bufferSize++] = (byte) s;
    buffer[bufferSize++] = (byte) (s >> 8); // little Endian

    // send to sound card if buffer is full
    if (bufferSize >= buffer.length) {

      // NullPointerException
      line.write(buffer, 0, buffer.length);
      bufferSize = 0;
    }
  }

  /** This main was generated by ARG-V */
  public static void main(String[] args) throws Exception {
    play(Verifier.nondetDouble());
  }
}
